# 2.1 数据操作 (Data Manipulation)
本 Notebook 包含《动手学深度学习》(D2L) 官方教材第 2.1 节的核心张量操作。

## 2.1.1 入门：张量的创建与形状属性

In [1]:
# 【所属小节】2.1.1 入门
# 【作用说明】使用 arange 创建包含 0~11 连续整数的 1 维向量
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
# 【所属小节】2.1.1 入门
# 【作用说明】查看张量的各轴维度大小（形状）
x.shape

torch.Size([12])

In [3]:
# 【所属小节】2.1.1 入门
# 【作用说明】获取张量中包含的元素总个数（标量数值）
x.numel()

12

In [4]:
# 【所属小节】2.1.1 入门
# 【作用说明】在不改变元素内容的前提下，改变张量的形状（变为 3行4列 矩阵）
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
# 【所属小节】2.1.1 入门
# 【作用说明】创建全 0 张量（常用作权重初始占位符）
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
# 【所属小节】2.1.1 入门
# 【作用说明】创建全 1 张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
# 【所属小节】2.1.1 入门
# 【作用说明】创建均值为0、标准差为1的标准正态分布随机张量（常用于模型权重随机初始化）
torch.randn(3, 4)

tensor([[-1.3810,  1.0856,  0.5973, -1.3981],
        [-0.5878, -0.3650,  1.1864, -0.0211],
        [ 0.1354,  0.9740,  0.3523, -1.4075]])

In [8]:
# 【所属小节】2.1.1 入门
# 【作用说明】通过 Python 原生嵌套列表直接精确指定数值创建张量
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 运算符：按元素数学计算与张量拼接

In [9]:
# 【所属小节】2.1.2 运算符
# 【作用说明】按元素（Element-wise）执行常见的加、减、乘、除、指数幂运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [10]:
# 【所属小节】2.1.2 运算符
# 【作用说明】使用 torch.cat 分别沿行（dim=0，上下堆叠）和沿列（dim=1，左右并排）拼接两个张量
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [11]:
# 【所属小节】2.1.2 运算符
# 【作用说明】通过逻辑运算符比较两张量，输出布尔张量（True/False）
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
# 【所属小节】2.1.2 运算符
# 【作用说明】对张量中的所有元素求和，输出 0 维标量
X.sum()

tensor(66.)

## 2.1.3 广播机制 (Broadcasting)

In [13]:
# 【所属小节】2.1.3 广播机制
# 【作用说明】构造形状不同的两个张量：a为 (3, 1)，b为 (1, 2)
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
# 【所属小节】2.1.3 广播机制
# 【作用说明】触发自动广播：a 复制列变成 (3, 2)，b 复制行变成 (3, 2)，相加得到 (3, 2)
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 索引与切片 (Indexing and Slicing)

In [15]:
# 【所属小节】2.1.4 索引与切片
# 【作用说明】访问末尾行元素 X[-1]，以及区间切片 X[1:3]（提取第 1 行和第 2 行）
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [16]:
# 【所属小节】2.1.4 索引与切片
# 【作用说明】通过坐标精确修改单个元素值（将第 1 行第 2 列元素改为 9）
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
# 【所属小节】2.1.4 索引与切片
# 【作用说明】为多个元素/切片区域批量赋相同数值（将第 0 行和第 1 行全部置为 12）
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 节省内存与原地操作 (In-place Operations)

In [18]:
# 【所属小节】2.1.5 节省内存
# 【作用说明】普通赋值 Y = Y + X 会分配新内存，导致前后内存地址 id(Y) 改变
before = id(Y)
Y = Y + X
id(Y) == before  # 结果为 False，分配了新内存

False

In [19]:
# 【所属小节】2.1.5 节省内存
# 【作用说明】切片写入 Z[:] = X + Y 可以在预先分配好的内存中原地重写，内存地址不变
Z = torch.zeros_like(Y)
print('写入前 id(Z):', id(Z))
Z[:] = X + Y
print('写入后 id(Z):', id(Z))  # 地址完全相同！

写入前 id(Z): 2169772279888
写入后 id(Z): 2169772279888


In [20]:
# 【所属小节】2.1.5 节省内存
# 【作用说明】运算符 X += Y 是原生原地操作（In-place），同样不产生内存重分配
before = id(X)
X += Y
id(X) == before  # 结果为 True

True

## 2.1.6 转换为其他 Python 对象

In [21]:
# 【所属小节】2.1.6 对象转换
# 【作用说明】Torch 张量与 NumPy 数组（ndarray）相互无缝转换
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [22]:
# 【所属小节】2.1.6 对象转换
# 【作用说明】使用 item() 或 float() 将单元素张量转换为 Python 原生标量数值
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)