# 2.3 线性代数 (Linear Algebra)

本 Notebook 对应《动手学深度学习》(D2L) 官方教程第 2.3 节。
包含：**标量、向量、矩阵、张量、张量算法基本性质、降维求和/均值、非降维广播** 的核心代码与详细注释。

## 2.3.1 标量 (Scalars)
标量由只有一个元素的张量表示，支持加、减、乘、除、乘方等常见数学运算。

In [ ]:
# ==============================================================================
# 【代码 2.3.1-1】标量基本数学运算 (Scalars Arithmetic)
# 功能：使用 torch.tensor 创建标量，并执行常见的四则运算及幂运算
# ==============================================================================
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y
# ------------------------------------------------------------------------------
# 【结果解读】返回四个标量张量：(tensor(5.), tensor(6.), tensor(1.5), tensor(9.))
# ==============================================================================

## 2.3.2 向量 (Vectors)
向量可以看作由标量值组成的列表，在代码中表示为一维张量。

In [ ]:
# ==============================================================================
# 【代码 2.3.2-1】创建一维向量
# 功能：使用 torch.arange 创建包含连续整数的一维张量（向量）
# ==============================================================================
x = torch.arange(4)
x
# ------------------------------------------------------------------------------
# 【结果解读】tensor([0, 1, 2, 3])
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.2-2】向量元素索引访问
# 功能：通过下标访问向量中的指定元素（下标从 0 开始）
# ==============================================================================
x[3]
# ------------------------------------------------------------------------------
# 【结果解读】访问下标为 3 的第 4 个元素，返回 tensor(3)
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.2-3】获取向量长度 (len)
# 功能：使用 Python 内置函数 len 获取向量包含的元素数量
# ==============================================================================
len(x)
# ------------------------------------------------------------------------------
# 【结果解读】返回整型数值 4
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.2-4】获取张量形状 (.shape)
# 功能：通过 .shape 属性查看向量各维度的长度
# ==============================================================================
x.shape
# ------------------------------------------------------------------------------
# 【结果解读】返回 torch.Size([4])，表示只有一个轴，长度为 4
# ==============================================================================

## 2.3.3 矩阵 (Matrices)
矩阵是具有两个轴的二维数组（行与列）。

In [ ]:
# ==============================================================================
# 【代码 2.3.3-1】创建矩阵并改变形状 (.reshape)
# 功能：生成 20 个连续整数，并将其重塑为 5 行 4 列的二维矩阵
# ==============================================================================
A = torch.arange(20).reshape(5, 4)
A
# ------------------------------------------------------------------------------
# 【结果解读】5x4 的矩阵，包含 5 行、4 列
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.3-2】矩阵转置 (.T)
# 功能：矩阵转置操作，交换矩阵的行和列（即 A^T）
# ==============================================================================
A.T
# ------------------------------------------------------------------------------
# 【结果解读】原 5x4 矩阵转置后变为 4x5 矩阵，原第 i 行变为第 i 列
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.3-3】对称矩阵示例
# 功能：构造一个方阵 B，验证对称矩阵特征 (B == B.T)
# ==============================================================================
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B
# ------------------------------------------------------------------------------
# 【结果解读】3x3 矩阵，沿主对角线完全对称
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.3-4】验证对称矩阵 (B == B.T)
# 功能：逐元素比对矩阵与其转置是否完全一致
# ==============================================================================
B == B.T
# ------------------------------------------------------------------------------
# 【结果解读】全部元素均为 True，证明该矩阵是对称矩阵
# ==============================================================================

## 2.3.4 张量 (Tensors)
张量是具有任意轴数的阶数更高的多维数组，如图像（通道数, 高度, 宽度）。

In [ ]:
# ==============================================================================
# 【代码 2.3.4-1】构造高维张量 (3阶张量)
# 功能：生成 24 个数，重塑为形状为 (2, 3, 4) 的三维张量
# ==============================================================================
X = torch.arange(24).reshape(2, 3, 4)
X
# ------------------------------------------------------------------------------
# 【结果解读】形状为 (2, 3, 4)，包含 2 个子矩阵，每个子矩阵 3 行 4 列
# ==============================================================================

## 2.3.5 张量算法的基本性质 (Basic Properties of Tensor Arithmetic)
按元素加法、按元素乘法（哈达玛积）与标量广播运算。

In [ ]:
# ==============================================================================
# 【代码 2.3.5-1】张量按元素相加与内存克隆 (.clone)
# 功能：相同形状的两个张量按元素相加；使用 .clone() 为新张量分配独立内存
# ==============================================================================
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B（深拷贝）
A, A + B
# ------------------------------------------------------------------------------
# 【结果解读】A + B 为对应位置元素直接相加，形状与 A 相同 (5, 4)
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.5-2】张量按元素乘法（哈达玛积 Hadamard Product）
# 功能：两个矩阵对应位置元素直接相乘，记作 A ⊙ B（注意：不是矩阵乘法）
# ==============================================================================
A * B
# ------------------------------------------------------------------------------
# 【结果解读】形状依然是 (5, 4)，每个位置等于 A[i, j] * B[i, j]
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.5-3】标量与张量的广播运算
# 功能：标量与张量进行加法/乘法运算时，标量会自动广播到张量的每个元素上
# ==============================================================================
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape
# ------------------------------------------------------------------------------
# 【结果解读】每个元素都加上/乘以 2，输出张量的形状保持为 (2, 3, 4)
# ==============================================================================

## 2.3.6 降维 (Reduction)
沿所有轴或指定轴进行求和、求均值，从而降低张量的维度（消除指定轴）。
- **降维核心法则（消消乐规则）**：指定 `axis=k` 求和/求均值，则输出形状中第 `k` 个维度的数字直接消失。

In [ ]:
# ==============================================================================
# 【代码 2.3.6-1】一维向量求和 (.sum)
# 功能：对一维向量所有元素求和，默认消除所有轴，输出标量
# ==============================================================================
x = torch.arange(4, dtype=torch.float32)
x, x.sum()
# ------------------------------------------------------------------------------
# 【结果解读】原形状 (4,) -> 求和后变为 0 维标量 tensor(6.)
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.6-2】二维矩阵全元素求和
# 功能：默认情况下，.sum() 沿所有轴求和降低维度，变为标量
# ==============================================================================
A.shape, A.sum()
# ------------------------------------------------------------------------------
# 【结果解读】原形状 torch.Size([5, 4])，所有元素总和为 tensor(190.)
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.6-3】指定 axis=0 沿行降维（按列求和）
# 功能：沿轴 0（行）压缩求和，轴 0 维数在输出形状中“消失”（5, 4）->（4,）
# 记忆技巧：“消除哪个轴，哪个轴就在形状中消失”
# ==============================================================================
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape
# ------------------------------------------------------------------------------
# 【结果解读】tensor([40., 45., 50., 55.])，形状为 torch.Size([4])
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.6-4】指定 axis=1 沿列降维（按行求和）
# 功能：沿轴 1（列）压缩求和，轴 1 维数在输出形状中“消失”（5, 4）->（5,）
# ==============================================================================
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape
# ------------------------------------------------------------------------------
# 【结果解读】tensor([ 6., 22., 38., 54., 70.])，形状为 torch.Size([5])
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.6-5】同时指定 axis=[0, 1] 沿多个轴求和
# 功能：同时沿轴 0 和轴 1 求和，等价于对所有元素求和
# ==============================================================================
A.sum(axis=[0, 1])  # 结果和 A.sum() 相同
# ------------------------------------------------------------------------------
# 【结果解读】输出 tensor(190.)
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.6-6】计算均值 (.mean 与 .numel)
# 功能：求张量所有元素的均值，等价于总和除以元素总个数 A.numel()
# ==============================================================================
A.mean(), A.sum() / A.numel()
# ------------------------------------------------------------------------------
# 【结果解读】输出 (tensor(9.5000), tensor(9.5000))
# ==============================================================================

In [ ]:
# ==============================================================================
# 【代码 2.3.6-7】沿指定轴计算均值 (axis=0)
# 功能：沿轴 0 计算均值，等价于 A.sum(axis=0) 除以轴 0 的长度 A.shape[0]
# ==============================================================================
A.mean(axis=0), A.sum(axis=0) / A.shape[0]
# ------------------------------------------------------------------------------
# 【结果解读】形状为 torch.Size([4])，按列求平均
# ==============================================================================

### 2.3.6.1 非降维求和 (keepdims 与广播机制)
通过设置 `keepdims=True`，求和或均值计算后轴数保持不变（被消除的轴变为长度 1），这对于后续的广播除法（如行归一化）至关重要。

In [27]:
# ==============================================================================
# 【代码 2.3.6-8】保持轴数不变的求和 (keepdims=True vs keepdims=False)
# 功能：通过设置 keepdims=True，求和后维度不消失，而是变为 1
# 对比说明：
# - keepdims=False: 形状变为 (5,)，在广播运算 A / sum_A 时会因维度不兼容报错！
# - keepdims=True:  形状保持为 (5, 1)，可以利用广播机制顺利执行 A / sum_A
# ==============================================================================
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape
# ------------------------------------------------------------------------------
# 【结果解读】形状为 torch.Size([5, 1])，保持了 2 维结构
# ==============================================================================

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [28]:
# ==============================================================================
# 【代码 2.3.6-9】利用广播机制进行归一化除法
# 功能：通过 keepdims=True 保持形状为 (5, 1)，利用广播将每行元素除以该行的总和
# ==============================================================================
A / sum_A
# ------------------------------------------------------------------------------
# 【结果解读】形状为 (5, 4)，每行所有元素之和归一化为 1.0
# ==============================================================================

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [31]:
# ==============================================================================
# 【代码 2.3.6-10】沿指定轴计算累加和 (.cumsum)
# 功能：沿着指定轴（例如 axis=0 沿行）计算元素的累加总和，不降低维度
# ==============================================================================
A.cumsum(axis=0), A
# ------------------------------------------------------------------------------
# 【结果解读】形状依然是 (5, 4)，每一行是前面所有行的累加和
# ==============================================================================

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [32]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [33]:
torch.sum(x * y)

tensor(6.)

In [35]:
A, x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [36]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [39]:
B= torch.ones(4,3)
A, B, torch.mm(A,B)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [40]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [41]:
torch.abs(u).sum()

tensor(7.)

In [42]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [52]:
len(X), X.shape, X.numel()

(2, torch.Size([2, 3, 4]), 24)

---
## 2.3 课后练习题代码实验验证
本部分为原书第 81 页练习题 1 ~ 8 题的代码验证实现。

In [ ]:
# ==============================================================================
# 【练习 1】证明 (A.T).T == A
# ==============================================================================
A = torch.arange(12).reshape(3, 4)
print("A:", A)
print("(A.T).T:", (A.T).T)
assert torch.equal((A.T).T, A)
# ------------------------------------------------------------------------------
# 【结论】转置两次复原，矩阵转置的转置为自身
# ==============================================================================

In [ ]:
# ==============================================================================
# 【练习 2】证明 A.T + B.T == (A + B).T
# ==============================================================================
B = torch.ones(3, 4)
assert torch.equal(A.T + B.T, (A + B).T)
print("转置的和等于和的转置：验证通过！")
# ==============================================================================

In [ ]:
# ==============================================================================
# 【练习 3】证明对任意方阵 A，A + A.T 总是对称矩阵
# ==============================================================================
Square_A = torch.randn(4, 4)  # 任意非对称随机方阵
M = Square_A + Square_A.T
print("M 是否等于 M.T:", torch.equal(M, M.T))
# ------------------------------------------------------------------------------
# 【结论】(A + A.T).T = A.T + (A.T).T = A.T + A = A + A.T = M，必然对称
# ==============================================================================

In [ ]:
# ==============================================================================
# 【练习 4 & 5】形状 (2, 3, 4) 的张量 X，len(X) 的输出及对应轴
# ==============================================================================
X = torch.arange(24).reshape(2, 3, 4)
print("len(X) =", len(X))
print("X.shape[0] =", X.shape[0])
assert len(X) == X.shape[0]
# ------------------------------------------------------------------------------
# 【结论】len(X) = 2，恒等于第 0 轴 (axis=0) 的长度
# ==============================================================================

In [ ]:
# ==============================================================================
# 【练习 6】运行 A / A.sum(axis=1) 的广播报错与 keepdims=True 修正
# ==============================================================================
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)

try:
    # 默认 keepdims=False，输出形状为 (5,)，无法与 (5, 4) 从右向左广播对齐
    err_res = A / A.sum(axis=1)
except RuntimeError as e:
    print("直接运行报错:", e)

# 正确做法：设置 keepdims=True，形状保持为 (5, 1)
correct_res = A / A.sum(axis=1, keepdims=True)
print("keepdims=True 归一化结果 shape:", correct_res.shape)
# ==============================================================================

In [ ]:
# ==============================================================================
# 【练习 7】形状 (2, 3, 4) 的张量在轴 0、1、2 上的求和形状（消消乐法则）
# ==============================================================================
print("X.shape:", X.shape)                                # (2, 3, 4)
print("axis=0 求和 shape (消去2):", X.sum(axis=0).shape)  # torch.Size([3, 4])
print("axis=1 求和 shape (消去3):", X.sum(axis=1).shape)  # torch.Size([2, 4])
print("axis=2 求和 shape (消去4):", X.sum(axis=2).shape)  # torch.Size([2, 3])
# ==============================================================================

In [ ]:
# ==============================================================================
# 【练习 8】高维张量 torch.linalg.norm 的行为与本质计算公式
# ==============================================================================
X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
norm_res = torch.linalg.norm(X)
manual_res = torch.sqrt(torch.sum(X ** 2))
print("torch.linalg.norm(X) =", norm_res)
print("手算 sqrt(sum(X**2))  =", manual_res)
assert torch.allclose(norm_res, manual_res)
# ------------------------------------------------------------------------------
# 【结论】计算的是全体元素平方和的平方根（Frobenius 范数 / 全局 L2 范数）
# ==============================================================================